/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d_sop;

import controls.Controls;
import controls.Database;
import java.awt.Color;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author mdcc_dinesh
 */
public final class main_window_cashier extends javax.swing.JFrame {

    public static double net_total = -1;
    private static int item_reg_id = -1;
    private static int grn_tbl_id = -1;
    private static double sell_price = -1;
    private static double qty_value = -1;
    private static int item_name = -1;

    private int itm_id;
    private double discount;
    private String disc_type;
    private String item;
    private String price;
    private boolean hasVFD;
    private Object net_amount;
    private Window credit_payment;
    private String sell_p;
    private String sell_pr;

    /**
     * Creates new form NewJFrame
     */
    public main_window_cashier() {
        initComponents();

        //Mouse courser default sett search bar *******************************
        txt_main_search.requestFocus();
        setExtendedState(MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_main_search = new javax.swing.JTextField();
        sell_price_disp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_hold = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_net_total = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_holded_invoice = new javax.swing.JTable();
        txt_qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        main_serch_item_tbl = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_added_items = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txt_bil_no_q1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ret_items_btn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 760));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));

        txt_main_search.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_main_search.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_main_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_main_search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_main_searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_main_searchFocusLost(evt);
            }
        });
        txt_main_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_main_searchActionPerformed(evt);
            }
        });
        txt_main_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_main_searchKeyReleased(evt);
            }
        });

        sell_price_disp.setBackground(new java.awt.Color(0, 0, 0));
        sell_price_disp.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        sell_price_disp.setForeground(new java.awt.Color(255, 255, 255));
        sell_price_disp.setText("0.00");
        sell_price_disp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sell_price_disp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sell_price_dispFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sell_price_dispFocusLost(evt);
            }
        });
        sell_price_disp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sell_price_dispActionPerformed(evt);
            }
        });
        sell_price_disp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sell_price_dispKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sell_price_dispKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("(F1) Search :");

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("QTY :");

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Sell Price :");

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Item Details ");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Loged user :");

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jButton1.setText("<html>Cash<br>Payment (+)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jButton5.setText("<html><font color=\"red\">Credit<br>Payment (-)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_hold.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        btn_hold.setText("Hold (*)");
        btn_hold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_holdActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jButton2.setText("Reset (F1)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Holded Invoices (F2)");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current Net Total :");

        txt_net_total.setBackground(new java.awt.Color(255, 153, 153));
        txt_net_total.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        txt_net_total.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tbl_holded_invoice.setBackground(new java.awt.Color(153, 153, 0));
        tbl_holded_invoice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tbl_holded_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><h4>Invoice No", "<html><h4>Date", "<html><h4>Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_holded_invoice.setRowHeight(22);
        tbl_holded_invoice.getTableHeader().setReorderingAllowed(false);
        tbl_holded_invoice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_holded_invoiceKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_holded_invoice);

        txt_qty.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txt_qty.setForeground(new java.awt.Color(255, 255, 255));
        txt_qty.setText("1");
        txt_qty.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_qty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_qtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_qtyFocusLost(evt);
            }
        });
        txt_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_qtyActionPerformed(evt);
            }
        });
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qtyKeyReleased(evt);
            }
        });

        main_serch_item_tbl.setBackground(new java.awt.Color(204, 204, 204));
        main_serch_item_tbl.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        main_serch_item_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "grn_tbl_id", "itm_id", "discount_price", "<html><h4>Item", "<html><h4>Available Qty", "<html><h4>Price", "<html><h4>Discount", "<html><h4>Batch", "disc_type", "sell_price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        main_serch_item_tbl.setRowHeight(30);
        main_serch_item_tbl.getTableHeader().setReorderingAllowed(false);
        main_serch_item_tbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                main_serch_item_tblKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(main_serch_item_tbl);
        if (main_serch_item_tbl.getColumnModel().getColumnCount() > 0) {
            main_serch_item_tbl.getColumnModel().getColumn(0).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(0).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(1).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(1).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(1).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(2).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(2).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(2).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(3).setResizable(false);
            main_serch_item_tbl.getColumnModel().getColumn(4).setResizable(false);
            main_serch_item_tbl.getColumnModel().getColumn(5).setResizable(false);
            main_serch_item_tbl.getColumnModel().getColumn(6).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(6).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(6).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(7).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(7).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(7).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(8).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(8).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(8).setMaxWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(9).setMinWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(9).setPreferredWidth(0);
            main_serch_item_tbl.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hold, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_main_search, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE))
                            .addComponent(sell_price_disp)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_net_total)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabel25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_main_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sell_price_disp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_hold, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_net_total, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_hold, jButton1, jButton2, jButton5});

        jPanel3.setBackground(new java.awt.Color(51, 121, 147));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Added Items (F5)");

        tbl_added_items.setBackground(new java.awt.Color(204, 255, 204));
        tbl_added_items.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tbl_added_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<html><h4>Item", "<html><h4>QTY", "<html><h4>Total", "<html><h4>Discount", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_added_items.setRowHeight(23);
        tbl_added_items.getTableHeader().setReorderingAllowed(false);
        tbl_added_items.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_added_itemsKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_added_items);
        if (tbl_added_items.getColumnModel().getColumnCount() > 0) {
            tbl_added_items.getColumnModel().getColumn(4).setMinWidth(0);
            tbl_added_items.getColumnModel().getColumn(4).setPreferredWidth(0);
            tbl_added_items.getColumnModel().getColumn(4).setMaxWidth(0);
        }

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 10)); // NOI18N
        jLabel24.setText("Invoice No. :");

        txt_bil_no_q1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_bil_no_q1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_bil_no_q1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_bil_no_q1FocusLost(evt);
            }
        });
        txt_bil_no_q1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bil_no_q1KeyReleased(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 0, 153));
        jLabel26.setText("Reprint Bill");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_bil_no_q1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_bil_no_q1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 204, 255));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Return");

        ret_items_btn.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ret_items_btn.setText("Sales Return");
        ret_items_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ret_items_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ret_items_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ret_items_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Day Off");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 214, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //calculate qty price ******************************************************
    public double cal_qty_price() {
        double item_sell_price = (sell_price * qty_value);
        double roundOff_item_sell_price = Math.round(item_sell_price * 100.0) / 100.0;
        return roundOff_item_sell_price;
    }

    //GET COUSTOMER BILL PRICE *************************************************
    public double coustomer_bill_price() throws Exception {
        double bill_price = 0.00;
        ResultSet bill_val = Database.getData("SELECT\n"
                + "r_invo_releted_itm.invo_no,\n"
                + "SUM(r_invo_releted_itm.invo_sell_price) AS total_bill_cost\n"
                + "FROM\n"
                + "r_invo_releted_itm\n"
                + "WHERE\n"
                + "r_invo_releted_itm.invo_no = '3'");
        if (bill_val.next()) {
            bill_price = bill_val.getDouble("total_bill_cost");
            System.out.println(bill_price);

        } else {
            System.out.println("Erro in query ....");
        }
        return bill_price;

    }

//    Search bar load tables ***************************************************
    public void item_bill_added_list_table() {
        try {
            ResultSet item_list = Database.getData("SELECT r_invo_releted_itm.invo_no, \n"
                    + "r_invo_releted_itm.invo_itm_id, \n"
                    + "r_invo_releted_itm.`status`, \n"
                    + "r_invo_releted_itm.invo_discount, \n"
                    + "r_invo_releted_itm.grn_item_reg_id, \n"
                    + " r_itm_reg.itm_name, \n"
                    + " r_invo_releted_itm.invo_itm_qty,\n"
                    + " r_invo_releted_itm.invo_sell_price,\n"
                    + " r_invo_releted_itm.invo_itm_data_id \n"
                    + " FROM \n"
                    + " r_invo_releted_itm \n"
                    + " INNER JOIN r_itm_reg ON r_invo_releted_itm.invo_itm_id = r_itm_reg.itm_id \n"
                    + " WHERE \n"
                    + " r_invo_releted_itm.invo_no = '3' \n"
                    + "  ORDER BY \n"
                    + " r_invo_releted_itm.invo_itm_data_id DESC");

            DefaultTableModel tMOdel = (DefaultTableModel) tbl_added_items.getModel();
            tMOdel.setRowCount(0);
            while (item_list.next()) {
                ArrayList arrList = new ArrayList();
                arrList.add(item_list.getString("itm_name"));
                arrList.add(item_list.getString("invo_itm_qty"));
                arrList.add(item_list.getString("invo_sell_price"));
                arrList.add(item_list.getString("invo_discount"));
                tMOdel.addRow(arrList.toArray());
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }

    }

//    Search bar load tables ***************************************************
    public void get_aval_items_by_serch() {
        String main_data = txt_main_search.getText();
        if (main_data.length() == 0) {
            DefaultTableModel tMOdel = (DefaultTableModel) main_serch_item_tbl.getModel();
            tMOdel.setRowCount(0);
        } else {
            try {
                ResultSet item_list = Database.getData("SELECT\n"
                        + "Sum(r_grn_itm_data.grn_qunt) AS grn_qunt,\n"
                        + "r_grn_itm_data.grn_itm_sell AS retail_prize,\n"
                        + "r_itm_reg.itm_name,\n"
                        + "r_grn_itm_data.grn_itm_data_id,\n"
                        + "r_grn_itm_data.grn_itm_id,\n"
                        + "r_itm_reg.discount,\n"
                        + "IF(r_itm_reg.discount_type='Value', CONCAT('Rs. ',r_itm_reg.discount), CONCAT(r_itm_reg.discount, ' %')) AS discount_disp,\n"
                        + "r_itm_reg.itm_code,\n"
                        + "r_itm_reg.discount_type,\n"
                        + "r_grn_itm_data.grn_ini_qty\n"
                        + "FROM r_itm_reg  \n"
                        + "INNER JOIN r_grn_itm_data ON r_grn_itm_data.grn_itm_id = r_itm_reg.itm_id\n"
                        + "WHERE  \n"
                        + "r_grn_itm_data.grn_qunt != '0'  \n"
                        + "AND ( r_itm_reg.itm_name LIKE '" + main_data + "%' OR  \n"
                        + "r_itm_reg.itm_code LIKE '" + main_data + "%')\n"
                        + "GROUP BY grn_itm_id\n"
                        + "ORDER BY r_itm_reg.itm_name ASC");
                DefaultTableModel tMOdel = (DefaultTableModel) main_serch_item_tbl.getModel();
                tMOdel.setRowCount(0);
                while (item_list.next()) {
                    ArrayList arrList = new ArrayList();
                    arrList.add(item_list.getString("grn_itm_data_id"));
                    arrList.add(item_list.getString("grn_itm_id"));
                    arrList.add(item_list.getString("discount"));
                    arrList.add(item_list.getString("itm_code") + " - " + item_list.getString("itm_name"));
                    arrList.add(item_list.getString("grn_qunt"));
                    arrList.add(item_list.getString("grn_ini_qty"));
                    arrList.add(item_list.getString("discount_disp"));
                    arrList.add("-");
                    arrList.add(item_list.getString("discount_type"));
                    arrList.add(item_list.getString("retail_prize"));

                    tMOdel.addRow(arrList.toArray());
                }

//                grn_tbl_id = Integer.parseInt(main_serch_item_tbl.getValueAt(0, 0).toString());
                itm_id = Integer.parseInt(main_serch_item_tbl.getValueAt(0, 1).toString());
                try {
                    discount = Double.parseDouble(main_serch_item_tbl.getValueAt(0, 2).toString());
                } catch (NumberFormatException x) {
                    discount = 0;
                }
                disc_type = main_serch_item_tbl.getValueAt(0, 8).toString();
                sell_p = main_serch_item_tbl.getValueAt(0, 9).toString();
                item = main_serch_item_tbl.getValueAt(0, 3).toString();
                sell_price_disp.setText(main_serch_item_tbl.getValueAt(0, 5).toString());

                price = sell_price_disp.getText();

            } catch (Exception ex) {
//                Logger.getLogger(main_window.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("no data found");
            }
        }
    }
    private void main_serch_item_tblKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_main_serch_item_tblKeyPressed
        //when click the enetre,will button focouce the QTY feild ************** 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_qty.requestFocus();
            txt_qty.selectAll();
            //GET TABALE ROW SELECTED VAL ******************************************
            int r;
            r = main_serch_item_tbl.getSelectedRow();
            String grn_tbl_i = main_serch_item_tbl.getValueAt(r, 0).toString();
            String g_item_id = main_serch_item_tbl.getValueAt(r, 1).toString();
            String item_n = main_serch_item_tbl.getValueAt(r, 3).toString();
            String sell_p = main_serch_item_tbl.getValueAt(r, 9).toString();

            //SET SELECTED VAL *****************************************************
            item_reg_id = Integer.parseInt(g_item_id);
            grn_tbl_id = Integer.parseInt(grn_tbl_i);
            sell_price = Double.parseDouble(sell_p);
            item_name = Integer.parseInt(item_n);

        }
    }//GEN-LAST:event_main_serch_item_tblKeyPressed

    //PAYMENT SELECT ***********************************************************

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_holdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_holdActionPerformed

    }//GEN-LAST:event_btn_holdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new cradit_payment(this, true).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new cash_payment(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sell_price_dispKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sell_price_dispKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_sell_price_dispKeyReleased

    private void sell_price_dispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sell_price_dispActionPerformed


    }//GEN-LAST:event_sell_price_dispActionPerformed

    private void sell_price_dispFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sell_price_dispFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_sell_price_dispFocusLost

    private void sell_price_dispFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sell_price_dispFocusGained

    }//GEN-LAST:event_sell_price_dispFocusGained

    private void txt_main_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_main_searchKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ADD) {
//            cal_spl_discount();
            if (hasVFD) {
                disp.ClearDisplay();
                disp.PrintFirstLine(StringUtils.rightPad("Net Total : " + String.valueOf(net_amount), 20, ""));
                disp.PrintSecondLine(StringUtils.center("", 20, ""));
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_MULTIPLY) {
//            hold_invoice();
        } else if (evt.getKeyCode() == KeyEvent.VK_SUBTRACT) {

            credit_payment.setSize(550, 280);
            credit_payment.setVisible(true);
            Controls.centerWindow(credit_payment, this);
            txt_pay_type.requestFocusInWindow();

        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            main_serch_item_tbl.requestFocusInWindow();
            main_serch_item_tbl.setRowSelectionInterval(0, 0);
        } else {
            get_aval_items_by_serch();
        }

    }//GEN-LAST:event_txt_main_searchKeyReleased

    private void txt_main_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_main_searchActionPerformed

    }//GEN-LAST:event_txt_main_searchActionPerformed

    private void txt_main_searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_main_searchFocusLost

    }//GEN-LAST:event_txt_main_searchFocusLost

    private void txt_main_searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_main_searchFocusGained

    }//GEN-LAST:event_txt_main_searchFocusGained

    private void tbl_holded_invoiceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_holded_invoiceKeyPressed

    }//GEN-LAST:event_tbl_holded_invoiceKeyPressed

    private void tbl_added_itemsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_added_itemsKeyPressed

    }//GEN-LAST:event_tbl_added_itemsKeyPressed

    private void txt_bil_no_q1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bil_no_q1FocusGained

    }//GEN-LAST:event_txt_bil_no_q1FocusGained

    private void txt_bil_no_q1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_bil_no_q1FocusLost

    }//GEN-LAST:event_txt_bil_no_q1FocusLost

    private void txt_bil_no_q1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bil_no_q1KeyReleased

    }//GEN-LAST:event_txt_bil_no_q1KeyReleased

    private void ret_items_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ret_items_btnActionPerformed

    }//GEN-LAST:event_ret_items_btnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed


    }//GEN-LAST:event_jButton7ActionPerformed

    private void sell_price_dispKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sell_price_dispKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tbl_added_items.requestFocus();
            double item_cost = (qty_value * sell_price);

            boolean add = Database.putData("INSERT INTO `r_invo_releted_itm` (`invo_no`, `invo_itm_id`, `invo_itm_qty`, `a_itm_sell_price`, `invo_sell_price`, `invo_cost_price`, `invo_discount`, `discount_type`, `grn_item_reg_id`, `status`, `type`, `date_time`) VALUES ('3', '" + item_reg_id + "', '" + qty_value + "','" + sell_price + "','" + item_cost + "', NULL, '0.00', NULL, '" + grn_tbl_id + "', '1', '-', '2017-11-24 08:23:08');");
            if (add) {
                JOptionPane.showMessageDialog(null, "Successfully added !", "Title", JOptionPane.INFORMATION_MESSAGE);
                item_bill_added_list_table();
                try {
                    double total_bill = coustomer_bill_price();
                    txt_net_total.setText(String.valueOf(total_bill));
                    net_total = total_bill;
                    
                } catch (Exception ex) {
                    Logger.getLogger(main_window_cashier.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro Uploading !", "Title", JOptionPane.INFORMATION_MESSAGE);
            }

        }

    }//GEN-LAST:event_sell_price_dispKeyPressed

    private void txt_qtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qtyFocusGained
        txt_qty.setBackground(Color.BLACK);
        txt_qty.setForeground(Color.white);
        txt_qty.selectAll();
        txt_main_search.setForeground(Color.black);
    }//GEN-LAST:event_txt_qtyFocusGained

    private void txt_qtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_qtyFocusLost
        txt_qty.setBackground(Color.white);
        txt_qty.setForeground(Color.black);
    }//GEN-LAST:event_txt_qtyFocusLost

    private void txt_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_qtyActionPerformed
        //        add_sell_item();
    }//GEN-LAST:event_txt_qtyActionPerformed

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            sell_price_disp.requestFocus();
            sell_price_disp.selectAll();
            String qty_c = txt_qty.getText();
            qty_value = Double.parseDouble(qty_c);

            double total_price = cal_qty_price();
            sell_price_disp.setText(String.valueOf(total_price));
        }

    }//GEN-LAST:event_txt_qtyKeyPressed

    private void txt_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyReleased
        int row = main_serch_item_tbl.getSelectedRow();
        try {
            if (hasVFD) {
                disp.ClearDisplay();
                disp.PrintFirstLine(StringUtils.rightPad(main_serch_item_tbl.getValueAt(row, 3).toString(), 20, ""));
            }
            if (hasVFD) {
                disp.PrintSecondLine(StringUtils.rightPad("QTY : " + txt_qty.getText(), 20, ""));

            }
        } catch (Exception ex) {
            Logger.getLogger(main_window.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_qtyKeyReleased

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_window_cashier.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_window_cashier.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_window_cashier.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_window_cashier.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main_window_cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_hold;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable main_serch_item_tbl;
    private javax.swing.JButton ret_items_btn;
    private javax.swing.JTextField sell_price_disp;
    private javax.swing.JTable tbl_added_items;
    private javax.swing.JTable tbl_holded_invoice;
    private javax.swing.JTextField txt_bil_no_q1;
    private javax.swing.JTextField txt_main_search;
    private javax.swing.JTextField txt_net_total;
    private javax.swing.JTextField txt_qty;
    // End of variables declaration//GEN-END:variables

  
 

