/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package d_sop;

import controls.Database;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mdcc_dinesh
 */
public class sub_cat extends javax.swing.JInternalFrame {

    /**
     * Creates new form sub_cat
     */
    public sub_cat() {
        initComponents();
        load_main_cat_combo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sub_cat_tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        edit_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sub_cat_name = new javax.swing.JTextField();
        main_cat_combo = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1340, 600));

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sub Category");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Main category        :");

        sub_cat_tbl.setBackground(new java.awt.Color(0, 204, 204));
        sub_cat_tbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sub_cat_tbl.setForeground(new java.awt.Color(255, 255, 255));
        sub_cat_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Main Category", "Sub Category"
            }
        ));
        sub_cat_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sub_cat_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sub_cat_tbl);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("DELETE");

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        edit_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_idActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sub category         :");

        main_cat_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        main_cat_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                main_cat_comboMousePressed(evt);
            }
        });
        main_cat_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main_cat_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edit_id, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(main_cat_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sub_cat_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addGap(200, 200, 200)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(main_cat_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_cat_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // creat id and value combo ***********************************************
    public static ArrayList<controls.ListItem> getItemsForCombo(String query, String col_ID, String col_Name) throws Exception {
        ArrayList<controls.ListItem> names = new ArrayList<>();
        Statement stmt = Database.getCon().createStatement();
        ResultSet rset = stmt.executeQuery(query);
        while (rset.next()) {
            controls.ListItem item = new controls.ListItem();
            item.setId(rset.getInt(col_ID));
            item.setName(rset.getString(col_Name));
            names.add(item);
        }
        return names;
    }

//    load main category combo ***************************************************
    public void load_main_cat_combo() {
        try {
            String query = "SELECT main_category.`name`,main_category.id FROM main_category ORDER BY main_category.`name` DESC, main_category.id DESC";
            ArrayList<controls.ListItem> itemsList = getItemsForCombo(query, "id", "name");
            DefaultComboBoxModel def = new DefaultComboBoxModel(itemsList.toArray());
            main_cat_combo.setModel(def);
             sub_category_table();
        } catch (Exception ex) {
        }
    }

    //Table load ***************************************************************
    private void sub_category_table() {
        controls.ListItem cus = (controls.ListItem) main_cat_combo.getSelectedItem();
        int main_cat_combo_id = cus.getId();

        try {
            ResultSet item_list = Database.getData("SELECT\n"
                    + "sub_category_id.sub_cat_id,\n"
                    + "main_category.`name`,\n"
                    + "sub_category_id.main_cat_id,\n"
                    + "sub_category_id.sub_cat_name\n"
                    + "FROM\n"
                    + "sub_category_id\n"
                    + "INNER JOIN main_category ON sub_category_id.main_cat_id = main_category.id\n"
                    + "WHERE\n"
                    + "main_category.id = '"+ main_cat_combo_id +"'\n"
                    + "ORDER BY\n"
                    + "main_category.id DESC");

            DefaultTableModel tMOdel = (DefaultTableModel) sub_cat_tbl.getModel();
            tMOdel.setRowCount(0);
            while (item_list.next()) {
                ArrayList arrList = new ArrayList();
                arrList.add(item_list.getString("sub_cat_id"));
                arrList.add(item_list.getString("name"));
                arrList.add(item_list.getString("sub_cat_name"));
                tMOdel.addRow(arrList.toArray());
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }


    private void sub_cat_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sub_cat_tblMouseClicked

        //GET TABALE ROW SELECTED VAL ******************************************
        int r;
        r = sub_cat_tbl.getSelectedRow();
        String id = sub_cat_tbl.getValueAt(r, 0).toString();
        String name = sub_cat_tbl.getValueAt(r, 2).toString();

        //SET SELECTED VAL *****************************************************
        edit_id.setText(id);
        sub_cat_name.setText(name);
    }//GEN-LAST:event_sub_cat_tblMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //GET VALUE IN ADD ITEM ************************************************
        String sub_cat = sub_cat_name.getText();
        controls.ListItem cus = (controls.ListItem) main_cat_combo.getSelectedItem();
        int main_cat_combo_id = cus.getId();

        if (sub_cat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Subcategory not to be empty!", "Erro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            boolean add_sub_cat = Database.putData("INSERT INTO `sub_category_id` (`sub_cat_name`, `main_cat_id`) VALUES ('" + sub_cat + "', '" + main_cat_combo_id + "')");
            if (add_sub_cat) {
                JOptionPane.showMessageDialog(null, "successfully added !", "Successfull", JOptionPane.INFORMATION_MESSAGE);
                sub_category_table();

            } else {
                JOptionPane.showMessageDialog(null, "Erro Uploading !", "Erro", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int showConfirmDialog = JOptionPane.showConfirmDialog(null, "Do you want to Update ?");

        //CHECK RETURN VAL FOR UPDATE ********************************************
        if (showConfirmDialog == 0) {
            String name = sub_cat_name.getText();
            String id = edit_id.getText();

            boolean update = Database.putData("UPDATE `sub_category_id` SET `sub_cat_name`='" + name + "' WHERE (`sub_cat_id`='" + id + "');");
            if (update) {
                JOptionPane.showMessageDialog(null, "successfully Updated !", "Title", JOptionPane.INFORMATION_MESSAGE);
                sub_category_table();
            } else {
                JOptionPane.showMessageDialog(null, "Update  Errro !", "Title", JOptionPane.INFORMATION_MESSAGE);
                sub_category_table();
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void edit_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edit_idActionPerformed

    private void main_cat_comboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_main_cat_comboMousePressed

    }//GEN-LAST:event_main_cat_comboMousePressed

    private void main_cat_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main_cat_comboActionPerformed
       sub_category_table();
    }//GEN-LAST:event_main_cat_comboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edit_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> main_cat_combo;
    private javax.swing.JTextField sub_cat_name;
    private javax.swing.JTable sub_cat_tbl;
    // End of variables declaration//GEN-END:variables

}
